import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { MainContent } from "@/blocks/MainContent/MainContent";


export default function Home() {
  return (
    <>
      <Head>
        <title>Test webvisor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <MainContent />
      </main>
    </>
  );
}
